name: customer_analytics
version: "1.0.0"

config-version: 2

profile: customer_analytics

model-paths:
  - models

macro-paths:
  - macros

target-path: target

clean-targets:
  - target
  - dbt_packages

models:
  customer_analytics:

    staging:
      +materialized: table

    intermediate:
      +materialized: table

    marts:
      +materialized: table